[package]
name = "netcrab"
version = "0.1.0"
description = "A tool suite for creating, visualizing and analyzing Petri nets"
repository = "https://github.com/hlisdero/netcrab/"
homepage = "https://github.com/hlisdero/netcrab/"
authors = ["Horacio Lisdero Scaffino <hlisdero@users.noreply.github.com>"]
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["petri-net", "dot", "pnml"]
categories = ["data-structures"]
edition = "2021"

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.24", features = ["derive"] }
env_logger = "0.9.3"
log = "0.4.17"
xml-rs = "0.8.4"

[dev-dependencies]
assert_cmd = "2.0.6"
assert_fs = "1.0.9"
predicates = "2.1.3"
